// <auto-generated />
using System;
using Deportivo.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deportivo.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221226040545_ModelData")]
    partial class ModelData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Accesorios", b =>
                {
                    b.Property<int>("id_acce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_acce"));

                    b.Property<int?>("DeportivoAccesorioid_depacce")
                        .HasColumnType("int");

                    b.Property<bool>("acce_act")
                        .HasColumnType("bit");

                    b.Property<string>("acce_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("acce_fecing")
                        .HasColumnType("datetime2");

                    b.Property<string>("acce_obs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_acce");

                    b.HasIndex("DeportivoAccesorioid_depacce");

                    b.HasIndex("id_acce")
                        .IsUnique();

                    b.ToTable("Accesorios");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Adicionales", b =>
                {
                    b.Property<int>("id_adicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_adicio"));

                    b.Property<int?>("PagoDetalleid_pagdet")
                        .HasColumnType("int");

                    b.Property<string>("adicio_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("adicio_est")
                        .HasColumnType("bit");

                    b.HasKey("id_adicio");

                    b.HasIndex("PagoDetalleid_pagdet");

                    b.HasIndex("id_adicio")
                        .IsUnique();

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_client"));

                    b.Property<int?>("Horarioid_hordep")
                        .HasColumnType("int");

                    b.Property<bool?>("client_act")
                        .HasColumnType("bit");

                    b.Property<string>("client_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_dociden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_obser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_telf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_tipdoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_client");

                    b.HasIndex("Horarioid_hordep");

                    b.HasIndex("id_client")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.DeportivoAccesorio", b =>
                {
                    b.Property<int>("id_depacce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_depacce"));

                    b.Property<bool>("depacce_act")
                        .HasColumnType("bit");

                    b.Property<DateTime>("depacce_fecingr")
                        .HasColumnType("datetime2");

                    b.HasKey("id_depacce");

                    b.HasIndex("id_depacce")
                        .IsUnique();

                    b.ToTable("Deportivo_Accesorio");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.EspacioDeportivo", b =>
                {
                    b.Property<int>("id_espdep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_espdep"));

                    b.Property<int?>("DeportivoAccesorioid_depacce")
                        .HasColumnType("int");

                    b.Property<int?>("Horarioid_hordep")
                        .HasColumnType("int");

                    b.Property<bool>("espdep_act")
                        .HasColumnType("bit");

                    b.Property<string>("espdep_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("espdep_fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_tipdep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_espdep");

                    b.HasIndex("DeportivoAccesorioid_depacce");

                    b.HasIndex("Horarioid_hordep");

                    b.HasIndex("id_espdep")
                        .IsUnique();

                    b.ToTable("Espacio_Deportivo");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Horario", b =>
                {
                    b.Property<int>("id_hordep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_hordep"));

                    b.Property<int?>("PagoDetalleid_pagdet")
                        .HasColumnType("int");

                    b.Property<string>("hordep_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("hordep_fecing")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("hordep_fecsal")
                        .HasColumnType("datetime2");

                    b.Property<string>("hordep_obse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_hordep");

                    b.HasIndex("PagoDetalleid_pagdet");

                    b.HasIndex("id_hordep")
                        .IsUnique();

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoCabecera", b =>
                {
                    b.Property<int>("id_pagcab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pagcab"));

                    b.Property<string>("pagcab_descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pagcab_est")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pagcab_feccrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("pagcab_fecemis")
                        .HasColumnType("datetime2");

                    b.Property<string>("pagcab_nro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pagcab_obs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pagcab_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_pagcab");

                    b.HasIndex("id_pagcab")
                        .IsUnique();

                    b.ToTable("Pago_Cabecera");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoDetalle", b =>
                {
                    b.Property<int>("id_pagdet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pagdet"));

                    b.Property<int?>("PagoCabeceraid_pagcab")
                        .HasColumnType("int");

                    b.Property<decimal>("pagdet_monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("pagdet_unidad")
                        .HasColumnType("int");

                    b.HasKey("id_pagdet");

                    b.HasIndex("PagoCabeceraid_pagcab");

                    b.HasIndex("id_pagdet")
                        .IsUnique();

                    b.ToTable("Pago_Detalle");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.TipoDeportivo", b =>
                {
                    b.Property<int>("id_tipdep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipdep"));

                    b.Property<int?>("EspacioDeportivoid_espdep")
                        .HasColumnType("int");

                    b.Property<bool>("tipdep_act")
                        .HasColumnType("bit");

                    b.Property<string>("tipdep_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tipdep");

                    b.HasIndex("EspacioDeportivoid_espdep");

                    b.HasIndex("id_tipdep")
                        .IsUnique();

                    b.ToTable("Tipo_Deportivo");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("id_tipdoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipdoc"));

                    b.Property<int?>("PagoCabeceraid_pagcab")
                        .HasColumnType("int");

                    b.Property<bool>("tipdoc_act")
                        .HasColumnType("bit");

                    b.Property<string>("tipdoc_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tipdoc");

                    b.HasIndex("PagoCabeceraid_pagcab");

                    b.HasIndex("id_tipdoc")
                        .IsUnique();

                    b.ToTable("Tipo_Documento");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Accesorios", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.DeportivoAccesorio", "DeportivoAccesorio")
                        .WithMany("Accesorios")
                        .HasForeignKey("DeportivoAccesorioid_depacce");

                    b.Navigation("DeportivoAccesorio");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Adicionales", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.PagoDetalle", "PagoDetalle")
                        .WithMany("Adicionales")
                        .HasForeignKey("PagoDetalleid_pagdet");

                    b.Navigation("PagoDetalle");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Cliente", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.Horario", "Horario")
                        .WithMany("Clientes")
                        .HasForeignKey("Horarioid_hordep");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.EspacioDeportivo", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.DeportivoAccesorio", "DeportivoAccesorio")
                        .WithMany("EspacioDeportivos")
                        .HasForeignKey("DeportivoAccesorioid_depacce");

                    b.HasOne("Deportivo.Web.Data.Entities.Horario", "Horario")
                        .WithMany("EspacioDeportivos")
                        .HasForeignKey("Horarioid_hordep");

                    b.Navigation("DeportivoAccesorio");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Horario", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.PagoDetalle", "PagoDetalle")
                        .WithMany("Horarios")
                        .HasForeignKey("PagoDetalleid_pagdet");

                    b.Navigation("PagoDetalle");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoDetalle", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.PagoCabecera", "PagoCabecera")
                        .WithMany("PagoDetalle")
                        .HasForeignKey("PagoCabeceraid_pagcab");

                    b.Navigation("PagoCabecera");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.TipoDeportivo", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.EspacioDeportivo", "EspacioDeportivo")
                        .WithMany("TipoDeportivos")
                        .HasForeignKey("EspacioDeportivoid_espdep");

                    b.Navigation("EspacioDeportivo");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.TipoDocumento", b =>
                {
                    b.HasOne("Deportivo.Web.Data.Entities.PagoCabecera", "PagoCabecera")
                        .WithMany("TipoDocumentos")
                        .HasForeignKey("PagoCabeceraid_pagcab");

                    b.Navigation("PagoCabecera");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.DeportivoAccesorio", b =>
                {
                    b.Navigation("Accesorios");

                    b.Navigation("EspacioDeportivos");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.EspacioDeportivo", b =>
                {
                    b.Navigation("TipoDeportivos");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Horario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("EspacioDeportivos");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoCabecera", b =>
                {
                    b.Navigation("PagoDetalle");

                    b.Navigation("TipoDocumentos");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoDetalle", b =>
                {
                    b.Navigation("Adicionales");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
