// <auto-generated />
using System;
using Deportivo.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deportivo.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221221220804_InicioMigra")]
    partial class InicioMigra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Accesorios", b =>
                {
                    b.Property<int>("id_acce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_acce"));

                    b.Property<bool>("acce_act")
                        .HasColumnType("bit");

                    b.Property<string>("acce_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("acce_fecing")
                        .HasColumnType("datetime2");

                    b.Property<string>("acce_obs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_acce");

                    b.ToTable("Accesorios");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Adicionales", b =>
                {
                    b.Property<int>("id_adicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_adicio"));

                    b.Property<string>("adicio_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("adicio_est")
                        .HasColumnType("bit");

                    b.HasKey("id_adicio");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_client"));

                    b.Property<bool>("client_act")
                        .HasColumnType("bit");

                    b.Property<string>("client_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_dociden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_obser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_telf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_tipdoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_client");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.DeportivoAccesorio", b =>
                {
                    b.Property<int>("id_depacce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_depacce"));

                    b.Property<bool>("depacce_act")
                        .HasColumnType("bit");

                    b.Property<DateTime>("depacce_fecingr")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_acce")
                        .HasColumnType("int");

                    b.Property<int>("id_espdep")
                        .HasColumnType("int");

                    b.HasKey("id_depacce");

                    b.ToTable("Deportivo_Accesorio");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.EspacioDeportivo", b =>
                {
                    b.Property<int>("id_espdep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_espdep"));

                    b.Property<bool>("espdep_act")
                        .HasColumnType("bit");

                    b.Property<string>("espdep_cod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("espdep_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("espdep_fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("espdep_tipo")
                        .HasColumnType("int");

                    b.HasKey("id_espdep");

                    b.ToTable("Espacio_Deportivo");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.Horario", b =>
                {
                    b.Property<int>("id_hordep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_hordep"));

                    b.Property<string>("hordep_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("hordep_fecing")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("hordep_fecsal")
                        .HasColumnType("datetime2");

                    b.Property<string>("hordep_obse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_clien")
                        .HasColumnType("int");

                    b.Property<int>("id_espdep")
                        .HasColumnType("int");

                    b.HasKey("id_hordep");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoCabecera", b =>
                {
                    b.Property<int>("id_pagcab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pagcab"));

                    b.Property<int>("id_tipodoc")
                        .HasColumnType("int");

                    b.Property<string>("pagcab_descr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pagcab_est")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pagcab_feccrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("pagcab_fecemis")
                        .HasColumnType("datetime2");

                    b.Property<string>("pagcab_nro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pagcab_obs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pagcab_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_pagcab");

                    b.ToTable("Pago_Cabecera");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.PagoDetalle", b =>
                {
                    b.Property<int>("id_pagdet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pagdet"));

                    b.Property<int>("id_adicio")
                        .HasColumnType("int");

                    b.Property<int>("id_hordep")
                        .HasColumnType("int");

                    b.Property<int>("id_pagcab")
                        .HasColumnType("int");

                    b.Property<decimal>("pagdet_monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("pagdet_unidad")
                        .HasColumnType("int");

                    b.HasKey("id_pagdet");

                    b.ToTable("Pago_Detalle");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.TipoDeportivo", b =>
                {
                    b.Property<int>("id_tipdep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipdep"));

                    b.Property<bool>("tipdep_act")
                        .HasColumnType("bit");

                    b.Property<string>("tipdep_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tipdep");

                    b.ToTable("Tipo_Deportivo");
                });

            modelBuilder.Entity("Deportivo.Web.Data.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("id_tipdoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipdoc"));

                    b.Property<bool>("tipdoc_act")
                        .HasColumnType("bit");

                    b.Property<string>("tipdoc_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tipdoc");

                    b.ToTable("Tipo_Documento");
                });
#pragma warning restore 612, 618
        }
    }
}
